pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: Commit
    displayName: Commit
    steps:
      - template: cache-docker-image-steps.yaml
        parameters:
          repository: mcr.microsoft.com/azure-cli
          tag: "2.9.1"

      - template: cache-docker-image-steps.yaml
        parameters:
          repository: apache/airflow
          tag: "2.0.1-python3.8"

      - task: AzureCLI@2
        displayName: Debug
        inputs:
          azureSubscription: "azure-data-engineering-sandbox-Data Engineering"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: ls -rla $(Pipeline.Workspace)/docker

      - task: AzureCLI@2
        displayName: Run
        inputs:
          azureSubscription: "azure-data-engineering-sandbox-Data Engineering"
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: ./batect run-cli

  - job: Docker
    displayName: Docker
    steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: "docker-de-demo-Data Engineering"